### ISSUE TITLE
Duplicate images in Nivo Slider

### ISSUE THREAD

**Issue by ankitaraikundalia** [ThemeFuse/Unyson-Sliders-Extension#10]
Hi,

I created a new slider selecting the type 2 slider from the 3 available i.e Nivo slider.
I uploaded 2 images manually and added this slider in a page using visual builder.

I have given a width of 1140 and height of 450 in the slider options of visual builder.

The slider doesn't work properly in responsive view and shows the same image twice as seen in the below screenshot:

![nivo-slider](https://cloud.githubusercontent.com/assets/9928664/7389352/bd4ccad0-ee8a-11e4-86c0-2390f0da1fbe.png)

The above screenshot is taken using browser width of 980px.

**Comment by llemurya** [comment]
@ankitaraikundalia the answer is the same as in #11 ,find on the internet how to make nivo slider responsive.If you resolve these issues , you can contribute to the community.

**Comment by dinhtungdu** [comment]
A simple fix for nivo slider to make it responsive is add this CSS:
```
.theme-default .nivoSlider img {
    height: auto !important;
}
```
