### ISSUE TITLE
sliders does not show up in dropdown

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson-Sliders-Extension#12]
hi there. I have a strange behaviour with Sliders extension. After I create any of the three types of sliders, with media categories auto populating method (not post taxonomy), the said sliders does not show up in dropdown when trying to insert. Sliders only work when I add manually each media. What I am doing wrong?

> https://wordpress.org/support/topic/sliders-extension

**Comment by bsusala** [comment]
This was solved already in https://github.com/ThemeFuse/Unyson/issues/485. You can safely close issue. Thanks
