### ISSUE TITLE
Overriding file named class-fw-shortcode-slider.php

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson-Sliders-Extension#13]
Hello there,
As you can see at the attachments, I created mirror folders and files in <code>framework-customizations</code> but it's not working.
![screen shot 2015-06-05 at 6 36 50 pm](https://cloud.githubusercontent.com/assets/3183635/8005294/a2ff5dc4-0bb2-11e5-9ac2-4da6d760fb60.png)
![screen shot 2015-06-05 at 6 39 42 pm](https://cloud.githubusercontent.com/assets/3183635/8005295/a307911a-0bb2-11e5-8add-3cc16421a4ea.png)
Any helps would be appreciated ! Thanks.

**Comment by llemurya** [comment]
@RayNguyen plese see this [video](https://youtu.be/60yJwL4EHl0).
