### ISSUE TITLE
Retrieve sliders by slider type.

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson-Sliders-Extension#14]
Hi there,
Eg: Users create sliders from both <code>bx-slider</code> and <code>nivo-slider</code>, but they are allowed to select <code>bx-slider</code> sliders only from shortcode (<code>nivo-slider</code> will be used for another purpose). How can I retrieve sliders from a specific slider type ?
Any helps would be appreciated. Thanks.

**Comment by llemurya** [comment]
@RayNguyen at the moment this feature don't exists, in next days I will add the method that will do this work.

**Comment by llemurya** [comment]
@RayNguyen you can use the function `get_populated_sliders()` to retrieve the sliders by slider type, see the below code.
```php
fw_print( fw_ext('slider')->get_populated_sliders( array( 'slider_types' => array( 'nivo-slider' ) ) ) );
```
