### ISSUE TITLE
Custom options in frontend

### ISSUE THREAD

**Issue by guezwho** [ThemeFuse/Unyson-Sliders-Extension#16]
How to name custom option array, for example: http://piccy.info/view3/9268023/a01d6828f47b7d5fc5a83737637cba14/orig/
in views/nivo-slider.php : http://piccy.info/view3/9268044/6e86178c0a06018b3e231cce0133931f/orig/
$data['slides'] like array for $tittle isn't working. 

And I don't find file with $data array, which mentioned in http://manual.unyson.io/en/latest/extension/slider/

**Comment by llemurya** [comment]
@guezwho `$data` variable which is an `array` is available in your `nivo-slider/views/nivo-slider.php` and the options that you set in the `custom.php` file goes to the `$data['slides']['extra']` , please answer if it helps and close the issue.

**Comment by guezwho** [comment]
Yes, $data['slides']['extra'] working for my options! Thank you!
