### ISSUE TITLE
Author role capabilities

### ISSUE THREAD

**Issue by ierpe** [ThemeFuse/Unyson-Sliders-Extension#17]
Hi,
I would like to give permission to the author role to edit the sliders, but when using "User Role Editor" plugin, I cannot see anything related to this ability.

Would you know how to achieve this?

**Comment by moldcraft** [comment]
Hello,

I am not expert in "User Role Editor" and don't have time to inspect it.

Slider post type is registered [here](https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/master/posts.php), if you know how to fix the problem, please create a pull request.
