### ISSUE TITLE
Slider description not showing

### ISSUE THREAD

**Issue by charlesjohn2004** [ThemeFuse/Unyson-Sliders-Extension#19]
Hi,
The slider description is not showing anywhere, can anyone pls help  -  http://www.outcrafter.com/olamwp3/

**Comment by moldcraft** [comment]
Hello,

More details please. How to reproduce the problem on our side (with exact steps and screenshots) ?

**Comment by charlesjohn2004** [comment]
![capture](https://cloud.githubusercontent.com/assets/12762009/20000904/bd39c99c-a29f-11e6-8986-5840f926fb5d.PNG)

I followed the usual steps which are;

1. Dashboard->Appearance->Sliders->Add new
2. Selected 'Slider Settings' type 2 (the one with the image of a car) and clicked 'Create' button
3. Added image, title and description as in the image attached.

**Comment by moldcraft** [comment]
> the one with the image of a car

I don't have such slider type. I don't have your theme. Please contact your theme author.

**Comment by charlesjohn2004** [comment]
Hi,
This is the default Unyson Slider extension I am using, There is no custom settings from theme's side (i am the theme author)

By default it has 3 slider types as in the pic attached. 
![capture](https://cloud.githubusercontent.com/assets/12762009/20001270/74394e6e-a2a1-11e6-8df3-10c49c5f0951.PNG)

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson-Sliders-Extension/commit/d9549708ce75494ff33abd753e6798f02b817b67

Please test if this is the expected behavior.

**Comment by charlesjohn2004** [comment]
<?php if (!defined('FW')) die('Forbidden'); ?>

<?php if (isset($data['slides'])): ?>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$('.nivoSlider').nivoSlider({effect:'fade'});
		});
	</script>
	
	<section class="wrap-nivoslider theme-default">
		<div class="nivoSlider">
			<?php foreach ($data['slides'] as $id => $slide): ?>
			<img  width="<?php echo esc_attr($dimensions['width']); ?>"
			      height="<?php echo esc_attr($dimensions['height']); ?>"
			      src="<?php echo esc_attr(fw_resize($slide['src'], $dimensions['width'], $dimensions['height'], true)); ?>"
			      alt="<?php echo esc_attr($slide['title']); ?>"
			      title="#nivo-<?php echo esc_attr($id); ?>" />
			<?php endforeach; ?>
		</div>
		<?php foreach ($data['slides'] as $id => $slide): ?>
		<div id="nivo-<?php echo esc_attr($id) ?>" class="nivo-html-caption">
			<span><?php echo $slide['title'] ?></span>
		</div>
		<?php endforeach; ?>
	</section>
	
<?php endif; ?>

This is the code in that file, doesn't mention description anywhere.

Unyson version 2.6.8. Installed the slider extension today.

**Comment by moldcraft** [comment]
I just made the changes, they are not included in live version.

[Download latest dev version](https://github.com/ThemeFuse/Unyson-Sliders-Extension/archive/master.zip) and extract in `wp-content/plugins/unyson/framework/extensions/media/extensions/slider`

**Comment by charlesjohn2004** [comment]
thank you :)
