### ISSUE TITLE
The Sliders need to be a shortcode

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson-Sliders-Extension#5]
Sliders need to be a shortcode like Contact Forms. The Sliders menu needs to disappear from the Appearance and user will be able to use the sliders only with the Page builder like you do with contact forms.

**Comment by albertso** [comment]
I agree that sliders should be a shortcode, one should be able to create a slider on any page.

I also think it's ok that sliders have their own post-type, this way it's easier to re-utilize them.
`fw-slider` post_type could be a wrapper for individual shortcodes.

BTW, could we have Slider Items with features like Page Sections?
Being able to layout columns and insert all the available shortcodes in each Item would be very useful.

In fact I have used sections before as "items" of a slider (a bit hacky), by opening and closing container div on first and last section. I use the [section] options to store each item background, title, etc.

I don't see why slider items don't take advantadge of a similar feature.

**Comment by albertso** [comment]
It also helps to put Sliders in a more coherent place in the menu, instead of under Appearance:

    // framework-customizations/extensions/media/extensions/slider/posts.php

    // re-register fw-slider post-type, changing the menu location and icon_dir

    $name = fw()->extensions->get('slider')->get_post_type();
    $type = get_post_type_object( $name );

    if (!empty($type)) {
        $type = (array) $type;
        $type['show_in_menu'] = current_user_can('switch_themes') ? true : null;
        $type['menu_icon'] = 'dashicons-images-alt2';
        $type['menu_position'] = 20;
        $type['supports'] = array('');
        $type['capabilities'] = array(
            'edit_post'         => 'edit_pages',
            'read_post'         => 'edit_pages',
            'delete_post'       => 'edit_pages',
            'edit_posts'        => 'edit_pages',
            'edit_others_posts' => 'edit_pages',
            'publish_posts'     => 'edit_pages',
            'read_private_posts'=> 'edit_pages',
            'read'                  => 'edit_pages',
            'delete_posts'          => 'edit_pages',
            'delete_private_posts'  => 'edit_pages',
            'delete_published_posts'=> 'edit_pages',
            'delete_others_posts'   => 'edit_pages',
            'edit_private_posts'    => 'edit_pages',
            'edit_published_posts'  => 'edit_pages',
        );
        register_post_type($name, $type);
    }

![sliders](https://cloud.githubusercontent.com/assets/1270475/10859563/e8b5daa8-7f5e-11e5-926c-c7119c51f8f1.JPG)
