### ISSUE TITLE
Overriding default options.

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson-Sliders-Extension#6]
Hi there, 
Thanks for creating an awesome extension.
I would like to override default slider options. Eg: I don't need "Description" textarea, but "Subtitle" text field right below "Title", and a "Background image" option right below "Image".
How can I do that ?
Any help would be appreciated ! Thanks !

**Comment by llemurya** [comment]
First part at your answer is represented in this [screen](http://static.md/2a7a143036a77212304ad049aad9fb47#).

**Comment by llemurya** [comment]
The second part to your question , how to remove title and description, create a function like this
```php
if(!function_exists('fw_theme_rayNguen_slider_population_method_custom_options')) :
	function fw_theme_carousel_slider_population_method_custom_options($arr) {
		/**
		 * Filter for disable standard slider fields for carousel slider
		 * @param array $arr
		 */
		unset(
			$arr['wrapper-population-method-custom']['options']['custom-slides']['slides_options']['title'],
			$arr['wrapper-population-method-custom']['options']['custom-slides']['slides_options']['desc']
		);

		return $arr;
	}

	// Canonical name 'fw_ext_{$slider_name}_population_method_{$population_method_name}_options'
	// ex: $slider_name = 'jw_carousel'; $population_method_name = 'custom'; name of the filter would be
	// 'fw_ext_jw_carousel_population_method_custom_options'
	add_filter( 'fw_ext_rayNguen_slider_population_method_custom_options', 'fw_theme_rayNguen_slider_population_method_custom_options');
endif;
```

**Comment by danyj** [comment]
info above is incorrect the function itself is not used in the filter , this would be correct version 



	if(!function_exists('_thz_filter_slick_full_remove_defaults')) {
		function _thz_filter_slick_full_remove_defaults($arr) {
			/**
			 * Filter for disable standard slider fields for slick full slider
			 * @param array $arr
			 */
			unset(
				$arr['wrapper-population-method-custom']['options']['custom-slides']['slides_options']['title'],
				$arr['wrapper-population-method-custom']['options']['custom-slides']['slides_options']['desc']
			);
	
			return $arr;
		}
	
		// Canonical name 'fw_ext_{$slider_name}_population_method_{$population_method_name}_options'
		// ex: $slider_name = 'slick-full'; $population_method_name = 'custom'; name of the filter would be
		// 'fw_ext_slick_full_population_method_custom_options'
		add_filter( 'fw_ext_slick_full_population_method_custom_options', '_thz_filter_slick_full_remove_defaults');
	}
