### ISSUE TITLE
Thumbnail of slide

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson-Sliders-Extension#7]
Hi there,
![screen shot 2015-02-27 at 12 04 51 am](https://cloud.githubusercontent.com/assets/3183635/6397229/e57feb5e-be15-11e4-9856-fe5e3da99be3.png)
First, take a look at my attachment. As you can see, each slide will generate its thumbnail from "Image". My problem is: how can I use "Background image" for the slide's thumbnail instead ?
Any helps would be appreciated. Thank you very much.

**Comment by llemurya** [comment]
@RayNguyen please see at this [screen](http://static.md/70e93b933b7799605a8fad16a6053ae7#). Hope this help.

**Comment by RayNguyen** [comment]
Hi, @llemurya 
I meant in back-end side, the thumbnail with green border is from "Image", how can I make it load from "Background image" instead ?
Hope this makes sense. Thanks.

**Comment by llemurya** [comment]
@RayNguyen It is not possible at this moment, because it can be video or image. We plan in future to change the whole functionality of the slider , to be in pop up window, and I think at this step we did not change it, sorry.
