### ISSUE TITLE
Fatal error !

### ISSUE THREAD

**Issue by RayNguyen** [ThemeFuse/Unyson-Sliders-Extension#9]
Hi there,
Follow the developer manual documentation, I tried to create a custom simple slider in:
<code>framework-customizations/extensions/slider/extensions/custom-slider</code>
but I cannot get it to work because of this error:
<code>
Fatal error: Extension "slider" is already defined in "../wp-content/plugins/unyson/framework/extensions/media/extensions/slider" found again in "../wp-content/themes/mytheme/framework-customizations/extensions/slider" in ../wp-content/plugins/unyson/framework/core/components/extensions.php on line 166
</code>
Any helps would be appreciated. Thanks !

**Comment by RayNguyen** [comment]
I've just moved folder named <code>bx-slider</code> to
<code>framework-customizations/extensions/slider/extensions/</code>
and got the same issue.

**Comment by llemurya** [comment]
@RayNguyen try create your extension in `framework-customizations/extensions/media/extensions/slider/extensions/bx-slider` not in `framework-customizations/extensions/slider/extensions/`, the difference is that `media` folder is missing. Soon we will update the documentation ,Sorry for this wrong description in the documentation.

**Comment by RayNguyen** [comment]
Hi @llemurya , 
I tried to do this and it worked just fine with older Unyson's version, but not 2.2.0. You can move <code>bx-slider</code> to <code>framework-customizations/extensions/media/extensions/slider/extensions/</code> to see the difference.
Thanks.

**Comment by llemurya** [comment]
@RayNguyen in version 2.2.1 of Unyson this bug is fixed, please update to the leatest version.
